services:
    - docker

before_script:
    - whoami
    - chmod -R o+w .
    - ls -la . frontend
    - docker-compose up
    # wait for installation after containers are up
    - while ! ((docker logs frontend) | grep 'Ready'); do sleep 10; done
    - while ! ((docker logs wp-headless) | grep 'You can now log in'); do sleep 10; done

script:
    - curl localhost:3000 | grep 'Congratulations!'
