version: '3'

services:
    db-headless:
        container_name: db-headless
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        image: mariadb
        ports:
            - 3307:3306
    wp-headless:
        build: .
        command: bash -c 'install_wordpress && apache2-foreground'
        container_name: wp-headless
        depends_on:
            - db-headless
        environment:
            - WORDPRESS_ADMIN_USER
            - WORDPRESS_ADMIN_PASSWORD
            - WORDPRESS_ADMIN_EMAIL
            - WORDPRESS_DB_HOST
            - WORDPRESS_DB_NAME
            - WORDPRESS_DB_PASSWORD
            - WORDPRESS_DB_USER
            - WORDPRESS_DEBUG
            - WORDPRESS_DESCRIPTION
            - WORDPRESS_PERMALINK_STRUCTURE
            - WORDPRESS_TITLE
            - WORDPRESS_URL
        ports:
            - 8080:80
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
            - ./docker/postlightheadlesswpstarter.wordpress.xml:/var/www/postlightheadlesswpstarter.wordpress.xml
            - ./docker/plugins:/var/www/plugins
    frontend:
        command: bash -c 'yarn && yarn start'
        container_name: frontend
        expose:
            - 3000
        image: node
        ports:
            - 3000:3000
        user: node
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app
